### ISSUE TITLE
Error reading from Google PubSub

### ISSUE THREAD

**Issue by ariguillegp** [codeonline-io/falco-gke-audit-bridge#1]
I am trying to read k8s audit events from a topic in Google PubSub using falco-gke-audit-bridge to inject events into Falco for further processing but I am getting the following errors:

`kubectl logs falco-ctmnt -c falco-gke-audit-bridge -nmon -f                                                                                            
info: Log level: info
info: Application started in 130ms
error: Failed to convert event 1sdpqvag1bd7hxd message=Cannot read property 'methodName' of undefined, stack=TypeError: Cannot read property 'methodName' of undefined
    at AuditService.convertAuditEvent (/app/audit.service.js:154:45)
    at AuditService.handleMessage (/app/audit.service.js:110:45)
    at Subscription.<anonymous> (/app/audit.service.js:97:86)
    at Subscription.emit (events.js:198:13)
    at Subscriber.Subscription._subscriber.on.on.message (/app/node_modules/@google-cloud/pubsub/build/src/subscription.js:199:44)
    at Subscriber.emit (events.js:198:13)
    at process.nextTick (/app/node_modules/@google-cloud/pubsub/build/src/lease-manager.js:192:53)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error: Failed to convert event 1sdpqvag1bd7hxb message=Cannot read property 'methodName' of undefined, stack=TypeError: Cannot read property 'methodName' of undefined
    at AuditService.convertAuditEvent (/app/audit.service.js:154:45)
    at AuditService.handleMessage (/app/audit.service.js:110:45)
    at Subscription.<anonymous> (/app/audit.service.js:97:86)
    at Subscription.emit (events.js:198:13)
    at Subscriber.Subscription._subscriber.on.on.message (/app/node_modules/@google-cloud/pubsub/build/src/subscription.js:199:44)
    at Subscriber.emit (events.js:198:13)
    at process.nextTick (/app/node_modules/@google-cloud/pubsub/build/src/lease-manager.js:192:53)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

Some context: I have Falco deployed as a DaemonSet in GKE, K8s audit logs redirected from StackDriver to PubSub and a falco-gke-audit-bridge container to read and convert such events for extra processing in Falco.

**Comment by steven166** [comment]
Could you show the audit log with insertId "1sdpqvag1bd7hxd" in Stackdriver?
You can mask fields that contain sensitive data.

**Comment by ariguillegp** [comment]
`{
 insertId: "1sdpqvag1bd7hxd"  
 jsonPayload: {
  apiVersion: "v1"   
  involvedObject: {
   apiVersion: "autoscaling/v2beta2"    
   kind: "HorizontalPodAutoscaler"    
   name: "idx-audit"    
   namespace: "op"    
  }
  kind: "Event"   
  message: "deployments/scale.apps "idx-audit" not found"   
  metadata: {
   name: "idx-audit.15e08e3f253315d8"    
   namespace: "op"    
  }
  reason: "FailedGetScale"   
  source: {
   component: "horizontal-pod-autoscaler"    
  }
  type: "Warning"   
 }
 logName: ".../logs/events"  
 resource: {
  labels: {
   cluster_name: "CLUSTERNAME"    
   location: "LOCATION"    
   project_id: "PROJECT"    
  }
  type: "k8s_cluster"   
 }
 severity: "WARNING"  
 timestamp: "2019-12-26T05:39:38Z"  
}`

**Comment by steven166** [comment]
This seems to be a Kubernetes Event object instead of an Audit log. 
Could you make sure the filter of the logging sink/exporter is set correctly: https://github.com/codeonline-io/falco-gke-audit-bridge/blob/master/deploy/terraform/audit-pubsub.tf#L20

**Comment by ariguillegp** [comment]
this is the filter I am using, it looks fine:
`resource.type="k8s_cluster"
resource.labels.location="LOCATION"
resource.labels.cluster_name="CNAME"
insertId="1sdpqvag1bd7hxd"`
is there anything else I am missing?

**Comment by steven166** [comment]
Maybe you need to add this filter to the query: 
```
protoPayload.@type:"type.googleapis.com/google.cloud.audit.AuditLog"
```

**Comment by husnialhamdani** [comment]
Hi @steven166 and @ariguillegp, 
I'm having the exact same issue `message=Cannot read property 'methodName' of undefined`, what the steps to resolve the issue?

Thanks

**Comment by steven166** [comment]
Hi @husnialhamdani, please refer to my previous comment.
